"""[update] Updated CourseProfile

Revision ID: 1e8347aa8606
Revises: 890a1c58511c
Create Date: 2025-11-01 14:00:33.828487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e8347aa8606"
down_revision: Union[str, Sequence[str], None] = "890a1c58511c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "class_profiles", sa.Column("profile", sa.String(length=50), nullable=False)
    )
    op.alter_column(
        "class_profiles",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "class_profiles", ["profile"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "class_profiles", type_="unique")
    op.alter_column(
        "class_profiles",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("class_profiles", "profile")
    # ### end Alembic commands ###
