"""Remove incorrect unique constraints from user_feedback table

Revision ID: 92a3910da503
Revises: b416390b0c5a
Create Date: 2025-11-02 23:20:18.315665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a3910da503'
down_revision: Union[str, Sequence[str], None] = 'b416390b0c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_feedback_assistant_message_key'), 'user_feedback', type_='unique')
    op.drop_constraint(op.f('user_feedback_session_id_key'), 'user_feedback', type_='unique')
    op.drop_constraint(op.f('user_feedback_user_message_key'), 'user_feedback', type_='unique')
    op.drop_constraint(op.f('user_feedback_username_key'), 'user_feedback', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_feedback_username_key'), 'user_feedback', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_feedback_user_message_key'), 'user_feedback', ['user_message'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_feedback_session_id_key'), 'user_feedback', ['session_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_feedback_assistant_message_key'), 'user_feedback', ['assistant_message'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
