"""[update] Updated Feedback table

Revision ID: b416390b0c5a
Revises: eab1e2f865b0
Create Date: 2025-11-01 20:48:43.569581

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b416390b0c5a"
down_revision: Union[str, Sequence[str], None] = "eab1e2f865b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_feedback", sa.Column("username", sa.String(length=50), nullable=False)
    )
    op.drop_constraint(
        op.f("user_feedback_user_name_key"), "user_feedback", type_="unique"
    )
    op.create_unique_constraint(None, "user_feedback", ["username"])
    op.drop_column("user_feedback", "user_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_feedback",
        sa.Column(
            "user_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "user_feedback", type_="unique")  # type: ignore
    op.create_unique_constraint(
        op.f("user_feedback_user_name_key"),
        "user_feedback",
        ["user_name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("user_feedback", "username")
    # ### end Alembic commands ###
