config:
  llm_model_config:
    creative_model:
      # google/gemini-2.0-flash-001, openai/gpt-oss-120b, x-ai/grok-4-fast
      model_name: openai/gpt-oss-20b
      model_provider: groq
      temperature: 0.2
      max_tokens: 2048
    structured_output_model:
      model_name: openai/gpt-oss-20b
      model_provider: openrouter
      temperature: 0.0
      max_tokens: 1024

  api_config:
    title: Data Processing API
    name: ${.title}
    description: API for processing large datasets
    version: v0.1.1
    status: healthy
    prefix: /api/v1

    # Server Settings
    server:
      host: 0.0.0.0
      port: 8000
      workers: 1
      reload: false

    # Middleware Configuration
    middleware:
      cors:
        allow_origins: ["*"]
        allow_credentials: true
        allow_methods: ["*"]
        allow_headers: ["*"]
